version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: beauty-care-db-container
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: beauty_care
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - beauty_care_network
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

  gradle:
    image: gradle:8.12.1-jdk21
    container_name: beauty-care-gradle
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - beauty_care_network
    command: ["gradle", "clean", "build", "test", "--no-daemon"]  # 빌드와 테스트를 동시에 실행

  app:
    image: beauty-care-app
    container_name: beauty-care-app-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - beauty_care_network
    ports:
      - 8080:8080
    volumes:
      - ./build/libs:/app/libs  # Gradle 빌드 결과로 생성된 .jar 파일을 app 컨테이너로 복사

networks:
  beauty_care_network:
    name: beauty_care_network

volumes:
  db_data:
