version: '3.8'

services:
  beauty-care-db-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: beauty_care_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  beauty-care-app-container:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - beauty-care-db-container
    ports:
      - "8080:8080"
    command: >
      sh -c "./gradlew test"