spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beauty_care
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

token:
  access: 31536000000