spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: beauty-care

springdoc:
  swagger-ui:
    path: /beauty-care/swagger.html

jwt:
  secret: "W8aQog6MTN0MoAtH+dRCvxUuIFLpmdtFwPrIf3EXcP/7doFiON4VKlfy9o6M+/LzqzqFrq5WJ52xWxvRUf79uQ=="

initial:
  password: qwer1234

cron:
  temp-file:
    delete: 0 0 5 * * *
  member:
    delete: 0 0 3 * * *

---
spring:
  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/beauty_care
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  cache:
    type: redis # redisConfig 활성화
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

token:
  access: 31536000000

file:
  upload:
    real:
      dir: ./UPLOAD/FILE/
    temp:
      dir: ./UPLOAD/TEMP/FILE

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://beauty-care-db-container:3306/beauty_care
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  data:
    redis:
      host: beauty-care-redis-container
      port: 6379
  cache:
    type: redis
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

token:
  access: 3600000  # 1시간

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update

# 테스트용
cron:
  member:
    delete: "*/5 * * * * *"

# 사용 안함.
file:
  upload:
    real:
      dir: ./TEST/UPLOAD/FILE/
    temp:
      dir: ./TEST/UPLOAD/TEMP/FILE

token:
  access: 3600000  # 1시간