spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: beauty-care

springdoc:
  swagger-ui:
    path: /beauty-care/swagger.html

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/beauty_care
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

token:
  access: 31536000000

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://beauty-care-db-container:3306/beauty_care
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

token:
  access: 31536000000

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create


token:
  access: 31536000000