spring:
  datasource:
    url: jdbc:mysql://beauty-care-db-container:3306/beauty_care
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

token:
  access: 31536000000

#springdoc:
#  swagger-ui:
#    path: /eng/swagger.html

#init:
#  password: a1234567890
#
#jwt:
#  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
#
#token:
#  access: 31536000000